# Powerlevel10k prompt (instant prompt must stay at top of main .zshrc)
# This file only handles the standard theme sourcing & configuration file.

if [ -f /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme ]; then
  source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
fi

# User customization (generated by p10k configure)
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"
